name: Simple Pipeline


on: 
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print a message
        run: echo "Hello! The pipeline is working successfully."
        
      - name: List files
        run: ls -la
